[build]
  base = "withjean-clone/"
  command = "npm run build"
  publish = "withjean-clone/build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[images]
  remote_images = [
    "https://ext.same-assets.com/**",
  ]
